- modules.nix
they are still pretty unstable and can fatally break systems
> remove content-addressed experimental features

- flake.nix
Importers are auxiliary functions of this library. It feels inconsistent when
they have the same visibility of primary (builder) functions.
> imp: remove importer from top level lib exports

- flake.lock
- flake.nix
Based on my understanding of NixOS/nix#2920, this would improve things. Since devos and anyone else using devlib usually only make use of the `lib` output, this would decrease download costs. Only the other outputs actually make use of `nixpkgs`, so nixpkgs shouldn't be pulled as a dependency from this library if only `devlib.lib` is used.
On a side note: I think lazy-fetching of inputs is a pretty good solution to the "development dependencies" issue.
> flake: use nixpkgs.lib for lib output

- src/importers.nix
- src/mkFlake/evalArgs.nix
This allows `importers.hosts` and `importers.overlays` to be used specifically for those api arguments.
What the goal is for devos's flake.nix:
```
channels.nixos = {
imports = [ (importers.overlays ./overlays) ];
overlays = [ ];
};
nixos = {
imports = [ (importers.hosts ./hosts) ];
hosts = { };
};
```
> importers: dedicated importers for api arguments

- src/pkgs-lib/shell/flk.sh
```
$ btrfs subvol show / >/dev/null; printf "%s\n" "$?"
ERROR: Could not search B-tree: Operation not permitted
1
```
Btrfs's `ioctl()` `BTRFS_IOC_TREE_SEARCH` requires elevation. `btrfs subvol show <path>` may be called by `nixos-generate-config`, and if `btrfs subvol show <path>` fails then `nixos-generate-config` fails.
Fixes `flk up` failures due to the presence of Btrfs volumes.
Replay of <https://github.com/divnix/devos/pull/281>.
> shell/flk: sudo nixos-generate-config

- src/mkFlake/default.nix
- src/mkFlake/evalArgs.nix
- src/pkgs-lib/shell/default.nix
Adds `devshellModules` api argument to add modules to the devshell. This also accepts `.toml` files which get auto-imported with devshell's `devshell.importToml`. To get that to work we have to pass `pkgs` as a specialArg so it can be used in an `imports` line.
> add devshellModules option to customize devshell

- src/pkgs-lib/shell/default.nix
fixes #21 
Makes it so the overlays of the default channel are included in the devshell - not installed, but available in modules
> shell: append overlays

- flake.lock
- flake.nix
- src/importers.nix
- src/mkFlake/default.nix
- src/mkFlake/evalArgs.nix
- src/pkgs-lib/shell/default.nix
- tests/default.nix
- tests/fullFlake/default.nix
- tests/fullFlake/devshell.toml
Introduces `devshell` namespace for `modules` and `externalModules`.
the import of .toml files no longer happens in evalArgs but instead happens as devshell modules are being exported and imported into shell.
depends on numtide/devshell#117
> Shell: setup export of devshell modules

- flake.lock
- flake.nix
- src/importers.nix
- tests/fullFlake/default.nix
- tests/fullFlake/hosts/com/example/myhost/default.nix
- tests/lib/default.nix
- hostnames are construed from a reverse DNS notation of folder names
BREAKING CHANGE (without practical impact):
fup needs to be udpated to parse the reverse DNS notation back into
a hostname DNS label + a DNS domain (to set networking.domain).
However, since until now, no recursive hosts where allowed, this
can be safely done soonishly.
> imp: make importers truely recursive

- src/pkgs-lib/shell/flk.sh
After discussion with @Pacman99 
the used command did not update as intended in one instance locally on my machine.
I din't investigate further, but `nix flake lock` seems the correct way to to this.
> fix: flk usage of lock update

- src/importers.nix
Allows you to have arbitrary folders that only get picked up if .nix files are in there. This could be useful for a folder dedicated to contains patches. And generally improves safety of the now fully recursive importers.
I decided to put this in rakeLeaves, since it makes no sense to rake pointless folders and the change propagates to all importers.
> importers: filter out empty attrsets

- flake.nix
Should help simplify #39 this means we can now access `fup-repl` in diggas devshell too.
Also we may as well offload some of the pkgs creation work to fup.
> flake: use fup for non-lib outputs

- src/modules.nix
- src/pkgs-lib/shell/default.nix
- src/pkgs-lib/shell/flk.sh
fixes #17
The command is just `repl`, I don't know if it needs to be `flk repl` since its a really generic command.
> generate registry and add fup-repl to env

- src/pkgs-lib/shell/flk.sh
Closes #41.
That was far easier than what I thought! bash scripting is really straight forward :smile: 
What this does:
- `flk vm HOST` generates the vm for the host under the vm folder, the link to the nix store result is named after the HOST.
- `flk vm-run HOST` generates the vm as `flk vm HOST` and runs the vm creating the disk image under the vm folder as `HOST.qcow2`
Here is the tree after doing a `flk vm-run NixOS`:
```
vm
├── NixOS -> /nix/store/<hash>-nixos-vm
└── NixOS.qcow2
```
This allows for fast iteration on the NixOS configuration which is super useful, I already love it! :heart:
> Added vm and vm-run commands to flk.sh

- src/pkgs-lib/shell/flk.sh
Closes #44.
This will make the command easier and more predictable.
We can also as a result add the iso folder in the devos gitignore.
> Changed output from nix build for iso and doi command

- flake.lock
- flake.nix
- src/mkFlake/default.nix
- src/modules.nix
- src/pkgs-lib/shell/flk.sh
- tests/fullFlake/modules/customBuilds.nix
Idea is that we create an entry in `system.build` for every format in nixos-generators. Also introduce `config.lib.digga.mkBuild` so devos's customBuilds doesn't have to re-implement the logic.
closes #49 cc @Lassulus
> Add default customBuilds from nixos-generators

- src/mkFlake/default.nix
- src/mkFlake/evalArgs.nix
In several places `mkFlake` assumes an valid value is set, here.
fixes: #76
```
nix develop
warning: Git tree '/home/blaggacao/ghq/github.com/blaggacao/devos' is dirty
error: The option `nixos.hostDefaults.channelName' is used but not defined.
```
> fix: make nixos.hostDefaults.channelName required

- doc/api-reference-devshell.md
- doc/api-reference-home.md
- doc/api-reference-nixos.md
- src/mkFlake/options.nix
I still prefer the `modules = ./modules/module-list.nix` pattern, this makes that possible without having to use `import`.
> mkFlake/options: add pathToOr for modules options

- flake.lock
- flake.nix
- modules/nix-config.nix
- shell.nix
This experimental feature has been removed from Nix in unstable versions recently, and with this set, it now pops up an unsupressable warning message. Not so bad on its own, but when using <kbd>Tab</kbd> completion it corrupts the output.
> nix: remove ca-references feature flag

- examples/hmOnly/home/users/testuser.nix
- src/mkFlake/options.nix
Type-check `home-manager` portable user configurations as modules (`moduleType`) rather than as functions evaluating to attribute sets (`functionTo attrs`).  This ensures that they get invoked with all expected module arguments (`pkgs`, `lib`, etc.).
Also update `./examples/hmOnly` so that the `testuser` configuration references the `pkgs` module arg, thus testing that the switch to `moduleType` works as intended.
Closes #119
> Ensure home-manager portable user configurations are called with expected module args

- src/modules.nix
> customBuilds: use mkDefault for freeform type

- flake.lock
- flake.nix
This means the only remaining part of digga lib that uses nixpkgs is deploy, which can hopefully be removed with use of the deploy overlay instead of `deploy.lib`.
A small piece of #115 focusing on the follows changes
> flake: remove anti-corruption layer and use nixlib
