divnix/digga

README.md
=> README.md: removed flake vcs info by mistake

shell.nix
Fix for issue #13 
```
error: unrecognised flag '-c'
```
=> Fix: nix run -> nix shell

flake.nix
Fix some things I noticed when porting [my configuration](https://github.com/jtojnar/nixfiles/commit/07aefeb5a8196139bfd5903de3ceaf6399298334#diff-5451c7b5e2e1f7c50be271bf7a786c04) to Flakes.
=> flake: Fix `nix flake check`

.gitattributes
A single star would only match a single level.
=> .gitattributes: match the entire secrets/** subtree

shell.nix
=> shell: alias rebuild to nixos rebuild

hosts/default.nix
=> home-manager: fix trying to import <nixpkgs>

flake.nix
Apps are automatically derived from the `packages` output. Only packages that contain an "$out/bin" are packaged as apps.
=> Add an `apps` output attribute set

flake.nix, lib/utils.nix, overlays/redshift.nix, overlays/retroarchBare.nix, pkgs/applications/blockchains/miningcore/default.nix
See https://github.com/numtide/flake-utils/pull/13.
=> use `flattenTreeSystem` for `packages` output

shell.nix
=> Shell: pass flags to iso build

shell.nix
better fix for #75
---
had no chance to test, yet. But am confident.
=> Fix realod

hosts/default.nix
=> hosts: enable redistributable firmware by default

flake.nix
Reverts nrdxp/nixflk#71
See #98
=> Revert "Add nrdxp cachix to substituter flake list"

hosts/default.nix
=> hosts: add nixpkgs to NIX_PATH

SUMMARY.md, doc/integrations/deploy.md, doc/start/bootstrapping.md, doc/start/index.md, doc/start/iso.md
=> doc: enact bootstrapping section

doc/CONTRIBUTING.md, doc/integrations/cachix.md, doc/start/from-nixos.md
Replace "your" by "you're" where it's meant to be a contraction of "you are" rather than a possessive pronoun.
=> doc: fix grammar: "your" -> "you're"

flake.lock, lib/devos/mkSuites.nix, lib/flake.nix, lib/lists.nix
this function collects profiles recursively
=> collect profiles recursively with lib function

flake.lock, flake.nix, lib/flake.nix, lib/generators.nix, lib/mkFlake/default.nix, lib/modules.nix
move both to be setup in template
only set home-manager options if they exist
=> improve home-manager and deploy-rs integration

doc/start/iso.md
=> Modified wording of iso documentation

overlays/various-flake-fixes.nix
fixes #315
@codygman can you test this locally if its a valid fix?
=> init: common flake compat fixes for other nixpkgs

flake.lock, flake.nix, overlays/various-flake-fixes.nix, shell/default.nix, shell/hooks/default.nix
- imp: add digga's nixConfig and patchedNix
- add flake's nixConfig values that go well with this repo
- fmt
=> config and nix patched

flake.lock, flake.nix, shell/default.nix
=> Update flake to use new modules options

flake.lock, flake.nix, overlays/overrides.nix, shell/devos.nix
- waiting for https://github.com/divnix/digga/pull/108
=> chore: update deploy-rs, nvfetcher, devshell

.github/workflows/check.yml, flake.lock
=> flake: update bud input and add check for bud

profiles/core/default.nix
=> profiles/core: add comments for each option

README.md
Lets get some examples of devos in the wild!
If you have a repository that uses digga, please comment the link or add a github suggestion to include it.
Its fine if your repository has completely diverged from devos, the more examples of usage the better.
=> README: Add flakes to "in the wild"

flake.lock
[This PR] was just merged on `flake-utils-plus` to fix an issue with the darwin integration.
This PR simply updates that dependency to make use of it.
=> Fix Darwin

devShell.nix
This method is a lot simpler and improves devShell readability
=> devShell: use --override-input to set digga url

.github/ISSUE_TEMPLATE/bug_report.md
as requested in https://github.com/divnix/digga/issues/474
=> Update issue template: adding `nix-info -m`
