- modules/default.nix
- modules/security/mitigations.nix
- profiles/misc/default.nix
- profiles/misc/disable-mitigations.nix
- profiles/misc/make-linux-fast-again.nix
Resolves #6 by breaking out the disabling of mitigations into it's own module.
Now users must explicitly accept the risk of disabling Spectre and Meltdown
mitigations with `security.mitigations.acceptRisk` in addtion to actually
disabling them with `security.mitigations.disable`.
> security#mitigations: init module

- README.md
- configuration.nix
- flake.lock
- flake.nix
- hosts/default.nix
Fixes #8 by importing a NUR as a flake input. Modules are accessible from `nurModules` and overlays from `nurOverlays` from within any NixOS module. In addition packages can be install with the usual `nur.repos.$user.$package`.
> flake: initial NUR support

- hosts/default.nix
As flakes cannot use `builtins.currentSystem`, there is no way as for now to use packages from a flake using `builtins.getFlake` because we need to pass a system to the result. (e.g. `myFlake.packages.x86_64-linux.myPackage`)
If we check the source code of [`lib.nixosSystem`](https://github.com/NixOS/nixpkgs/blob/3743c42f23767dca657f1a5d3eb67945e373ff94/flake.nix), we can see that `args` is passed to [`./nixos/lib/eval-config.nix`](https://github.com/NixOS/nixpkgs/blob/b77d8ead284c4193f84c82d2fcd4a3aa11fbf158/nixos/lib/eval-config.nix). In that file, `extraArgs` is defined, which says that args passed through this attribute will be distributed to each module loaded.
With my contribution, we can add system to defined nixos modules.
> Add extraArgs to lib.nixosSystem call to add system args

- flake.lock
- flake.nix
Also fixes #24 by using recommended home-manager
Now this error happens though:
```shell
rebuild niximg test
evaluating file '/nix/store/2qc98g8pw1yv3kvh1yczwdjazgj14rw4-nix-2.4pre20200721_ff314f1/share/nix/corepkgs/derivation.nix'
evaluating file '/nix/store/bn1v0x4df7ai5xz20ynjhpxwjsbz3kqi-source/flake.nix'
evaluating file '/nix/store/bn1v0x4df7ai5xz20ynjhpxwjsbz3kqi-source/hosts/default.nix'
... snip ...
evaluating file '/nix/store/9ify4gaqcpnxqwb7alkspwxqhzicrpgi-source/pkgs/os-specific/linux/wpa_supplicant/default.nix'
evaluating file '/nix/store/9ify4gaqcpnxqwb7alkspwxqhzicrpgi-source/pkgs/os-specific/linux/udisks/2-default.nix'
evaluating file '/nix/store/9ify4gaqcpnxqwb7alkspwxqhzicrpgi-source/nixos/modules/installer/tools/nixos-option/default.nix'
evaluating file …
```
> update to 20.09 to fix segfault

- DOC.md
Fixed one small typo in DOC.md.
> DOC.md: Fix declaration typo

- DOC.md
- flake.nix
- hosts/default.nix
- lib/utils.nix
Fixes #28 by adding an `externOverlays` list to easily import overlays from external flakes.
In general, the flake.nix was becoming pretty messy.
> flake: clean up by moving implementation to utils

- flake.lock
- flake.nix
- pkgs/applications/blockchains/miningcore/default.nix
- pkgs/applications/display-managers/sddm/themes/chili/default.nix
- pkgs/applications/window-managers/steamcompmgr/default.nix
- pkgs/data/fonts/dejavu-nerdfont/default.nix
- pkgs/misc/drivers/wii-u-gc-adapter/default.nix
- pkgs/shells/zsh/pure/default.nix
- pkgs/shells/zsh/purs/default.nix
This should resolve #17 and fix #34. NixOS is only supported on x86 Linux, so this does not affect nixosConfigurations. This only affects the `devShell` and `package` outputs. NixOS is pinned to x86_64 for now.
Every package is tested to ensure it is compatible with a given system based on its platform metadata _before_ it it added to that systems package set.
> initial multiArch support

- flake.nix
- hosts/default.nix
Fixes #44. Easily add external modules from other flakes by dropping them in the list.
> flake: add `externModules` list

- hosts/default.nix
Fix #46 by reverting commit 684804ebe026aaad2c6bbcff2166222ebff124d8.
If you need the value of `system`, use `pkgs.system` instead.
> Revert "Add extraArgs to lib.nixosSystem call to add system args."

- DOC.md
- README.md
- configuration.nix
HM moved to nix-community on Github. There is a 301 redirect, but I have no idea how long it will stay up, so it's better not to rely on it.
Things done:
> update home-manager urls

- lib/utils.nix
- overlays/pkgs.nix
since packages are exposed through output.packages by their own,
a second export through overlays.pkgs would be smudging the public api
of this repository.
> ref: remove overlay xref to pkgs

- flake.nix
- hosts/default.nix
- hosts/niximg.nix
We should be able to pull modules from master in a pinch. Just place a relative module path name in the `unstableModules` list in `hosts/default.nix`, it will be overriden.
For modules which are not included by default, such as the installable iso image modules, they can be pulled from anywhere via `unstableModulesPath`.
Fixes #63.
> Make modules overridable

- hosts/default.nix
In some occasions the module path was renamed.
To avoid conflicts, the old path must be disabled manually.
E.g.
```nix
{
unstableModules = [
"services/ttys/getty.nix"
];
addToDisabledModules = [
"services/ttys/agetty.nix"
];
}
```
> Hosts: fix mod override

- flake.nix
The baseline pkgs for own consumption is nixos, only pkgs/override.nix
provides a mechanism to "backport" packages from unstable.
Therefore, we should expose our packages to others in the same
context as we use them ourselves.
---
I was about to open an issue, yet I figured it would be more helpful to directly propose a PR, instead. Maybe this needs more preliminary discussion, though.
See also #76 (part about `master` vs `nixos` overlays)
---
Proporsal together with #78 
fix #76
> Evaluate exported pkgs against repo baseline nixos

- lib/utils.nix
master is only used in the context of `pkgs/override.nix`
and `unstableModulesPath`
and only within `./hosts`
Since [overlays exists that are incompatible between nixos and master
at evaluation time (sic!)](https://github.com/nrdxp/nixflk/issues/63#issuecomment-757566201), this together with #77 avoids evaluating
overlays against master all together.
---
Proposal to
fix #76
> Don't evaluate overlays on master

- .gitignore
- README.md
- shell.nix
Automatically generate a configuration for your current system using nixos-generate-config, placed in the `up` directory. A file is added in hosts/up-$(hostname).nix importing said configuration.
Useful for getting up and running quickly, but if the user intends to use more than one host, they should probably move the generated bits directly into their host config manually.
@blaggacao, would appreciate your input.
> shell: add `flk up` command

- flake.nix
As pointed out here numtide/flake-utils#17, apps are somewhat redundant and, for the sake of simplicity, should be removed for now.
.
Fixes #79
> flake: remove apps to reduce complexity

- README.md
- flake.lock
- flake.nix
- hosts/default.nix
- add nixos-hardware flake.
- configuration in hosts/default.nix to be able to include hardware
specifics per host.
- add corresponding documentation in readme
> flake/host: add nixos-hardware

- flake.nix
courtesy of: https://github.com/NixOS/nix/commit/343239fc8a1993f707a990c2cd54a41f1fa3de99
> Add nrdxp cachix to substituter flake list

- README.md
- hosts/default.nix
Just after you merged my PR I realised there is also a more an approach to include nixos-hardware more inline with the idea of falkes.
This basically means no paths are need to include the hardware configuration and looks a bit cleaner in my opinion.
> nixos-hardware: use the flake instead of a path

- .pre-commit-config.yaml
- flake.lock
- shell/default.nix
Since https://github.com/numtide/devshell/pull/63, git hooks where introduced into deshell.
They better encapsulate the development environment than pre-commit does. Notably, they are under nix control not under pre-commit control.
@zimbatm looks good, first adoption attempt in the wild :+1: Thx!
> shell: use devshell-native pre-commit hooks

- README.md
- flake.nix
- lib/default.nix
- shell/default.nix
Closes #83 
Working implementation of exporting home-manager only configurations. This exports to a non-official output of homeConfigurations, along with hmActivationPackages in the packages output. Both are an attrset of hosts then users
So if you were trying to build activationPackage for the host NixOS and user nixos, you can do:
`nix build ./#homeConfigurations.NixOS.nixos.home.activationPackage`
or 
`nix-build ./#hmActivation.NixOS.nixos'
This ones easier for debugging, because nix build will default to the packages output if homeConfiguration has any error and it won't say when it does so.
The flk script can then use the activation package to activate the home-manager configuration(not implemented yet).
There are a few more things to add like local nix registry and config with …
> users: Initial home-manager only configurations(non-nixos systems)

- profiles/core/default.nix
As discussed in related issues, this shouldn't be on by default and is likely a leftover from the earlier stages of the project.
> core: fix #115

- SUMMARY.md
- doc/integrations/deploy.md
- doc/integrations/index.md
- extern/default.nix
- flake.lock
- flake.nix
- lib/default.nix
- nix/ci.nix
- profiles/core/default.nix
- shell/default.nix
Managing servers remotely is a big usecase, and deploy-rs is a flake first deployment tool. By default, all nixosConfigurations are also setup as deploy-rs nodes.
You'll still need to do some manual ssh setup, but other than that, the system is ready to deploy.
> deploy-rs: init support

- hosts/NixOS.nix
- hosts/default.nix
- lib/default.nix
- profiles/README.md
- profiles/user
- suites/default.nix
> profiles: simplify profiles to suites

- README.md
- doc/flk/update.md
- flake.lock
- flake.nix
- lib/default.nix
- pkgs/README.md
- pkgs/flake.nix
- shell/flk.sh
Fixes #118.
Would appreciate any feedback before finalizing. 
My only nitpick is that I'd love to add the ability for `mkVersion` to pull a flake urls ref if one is given. For example, a flake url "github:owner/repo/version-tag" would generate the version: "version-tag". Doesn't seem like flake inputs keep the original ref though, only the sha, so we can't do this without parsing the lock file, or potentially filing an issue upstream to include this information.
> ##### _Note:_
> ~~This will break hercules-ci, since it currently relies on flake-compat, and this technique [breaks](https://discourse.nixos.org/t/possibility-for-subflakes/11589/6) flake-compat. So I'm kinda hesitant to merge unless a workaround is found.~~
/cc @benneti  @blaggacao @Pacman99
> pkgs: automatic source management

- hosts/default.nix
Get rid of the problematic entries, but keep `nixos` as a shortcut for the current `nixos` devos input. (e. g. `nix build nixos#firefox`). Resolves #142
> hosts: fix #142

- SUMMARY.md
- flake.nix
- lib/README.md
- lib/default.nix
A tiny step carved out of thought journey while working on #145.
Benefit: we can encourage/document to extend `./lib` more usefully:
example:
```nix
{ nixos, pkgs, ... }:
{
mkPlutoApp = pkgs.callPackage ./mkPlutoApp { };
}
```
> lib: can depend on pkgs (a la nixpkgs#pkgs/pkgs-lib)

- modules/security/mitigations.nix
the trailing newline will push other kernel params to another line, leading to something like:
```
/boot/loader/entries/nixos-generation-67.conf:7: Unknown line "loglevel=4", ignoring.
```
> remove trailing newline of cmdline in mitigations.nix

- doc/start/iso.md
- flake.nix
- lib/devos/devosSystem.nix
closes #190
Tested on my setup, considerably cuts times and only leaves one (noticable) download.
> iso: copy input closourse into iso to avoide re-download

- hosts/default.nix
should help with #163. Fixes #169
But either way this could be generally useful. I have one use case of setting up a minecraft bungeecord proxy with servers on different hosts.
> add hosts module arg

- hosts/default.nix
- lib/devos/devosSystem.nix
This is a fairly simple change that only changes the lib api for devosSystem. But doesn't add any features by itself. Hosts now pass modules to devosSystem as an attrset. And devosSystem just grabs all modules in the set and passes it to nixosSystem. 
I plan to use this in #197 to selectively import modules. And I think it could help with nix-darwin - and other config systems - support, since not all profiles and modules are config system agnostic. This could be a workaround to add rudimentary support for other config systems by only importing the necessary modules.
Overall I think its a useful change and extends the abilities of `devosSystem`
> hosts/devosSystem: pass modules as attrset

- flake.nix
- hosts/README.md
- hosts/default.nix
- lib/default.nix
- tests/default.nix
fixes #72 
also related, #125 
This allows users to set `nixpkgs.system` to any architecture exported by the nixpkgs flake and nixpkgs.pkgs will be set to that system.
I also added `multiPkgs` as a special arg and made `nixpkgs.pkgs` a default. So if someone wanted to do crossSystem builds or anything else with pkgs, that is also an option(eg. mobile-nixos!!).
> Multi-arch support for hosts(nixosConfigurations)

- lib/devos/devosSystem.nix
- lib/devos/mkProfileAttrs.nix
fixes #194
alternative to #197
<details>
<summary>was unrelated</summary>
Issue: https://github.com/divnix/devos/issues/204
Upstream Issue: https://github.com/NixOS/nixpkgs/issues/116938
</details>
```console
$ flk install POS
warning: you don't have internet access; disabling some network-dependent features
building the flake in path:/iso/devos?narHash=sha265-...
warning: you don't have internet access; disabling some network-dependent features
error: unable to download 'https://api.github.com/repos/NixOS/nixpkgs/df8e3...': Couldn't resolve host name (6)
```
&rarr; detailed rationale in the commit messages
:heart: @Pacman99 for the excellent and detailed discussions in #197 and the may ideas, suggestions and code.
> iso: avoid systemd service startup

- hosts/default.nix
fixes #208 
I think it was dropped during #157. It used to be added to nixosModules, but I think its better added to hosts, I don't see a reason to export the cachix module as an output.
> hosts: add cachix

- lib/lists.nix
Really simple, just don't error if path passed to pathsIn doesn't exist. This doesn't affect much, since the majority of folders in devos end up getting referenced in some way or another outside of a pathsIn call. But it will  help for users of mkDevos, so they can safely delete folders they don't want to use. 
Can test with current overlays folder in deovs, that only gets imported through a pathsIn call.
> lib/pathsIn: don't error if path doesn't exist

- lib/devos/mkPkgs.nix
nixpkgs applies overlays in the order given. This PR moves the lib extension overlay to be first so all subsequent overlays can access `dev` which is the devos lib.
> lib/mkPkgs: reorder overlays to get access to devos lib(dev)

- flake.lock
- lib/devos/devosSystem.nix
- tests/default.nix
> home-manager fixes

- lib/attrs.nix
So I learned about this myself while working on it. Nix has a thing called string context, where strings refer to various store paths that they used to contain. This is normally a good thing to guarantee purity, but flake outputs cannot contain store paths. So when `pathsToImportedAttrs` is passed a list of store paths, and is then used for a flake output, we get a very confusing error that the string refers to a store path - even though it doesn't look like it does! 
I think its good to review this as a separate Pr, since it requires calling an unsafe nix builtin.
> lib/pathsToImportedAttrs: discard string context in the names to prevent flake check error

- flake.lock
- flake.nix
- lib/attrs.nix
- lib/default.nix
I don't think we should flatten the system because if a user doesn't make a package a derivation in pkgs/default.nix we should trust that there is a reason for doing so. So instead this drops the flattenTreeSystem reference(and switches to flake-utils master branch) and replaces its usage with a custom function `filterPackages`. This function filter all packages that match three conditions;
- is a derivation
- not broken
- system is supported
In that order as to not cause errors when trying to reference non-derivation meta attributes.
And then also just dump *all* packages into legacy packages, so everything else is still accessible. I was considering removing the packages that are already in the packages output in legacyPackages, but I don't think its necessary since nix looks to the …
> Drop flattenTreeSystem and use custom function for filtering packages

- flake.nix
- lib/devos/mkPkgs.nix
- shell/default.nix
Changes mkPkgs to take extern, overrides, and pkgs as an argument. This improves their ability to be used as lib functions.
> lib/mkPkgs: don't import external files and get inputs as argument

- lib/attrs.nix
- lib/default.nix
- lib/devos/mkProfileAttrs.nix
- lib/devos/recImport.nix
- lib/lists.nix
- tests/lib.nix
After doing this for the second time, I realized it might be good to make a lib function for it and do it across lib.
Create a function called `safeReadDir` that only uses `builtins.readDir` if the path exists. With `optionalAttrs` any function that relies on the output won't fail since they still get an empty attrset.
Then replace all uses of `readDir` with the safe version.
> lib: only readDir if path exists with safeReadDir

- lib/devos/mkHosts.nix
- profiles/core/default.nix
- suites/default.nix
Prevents mkHosts subverting standard devos api to import core and add
all necessary core features to mkHosts, so core can be safely deleted in
suites
> make core an unecessary profile and add to suites

- flake.nix
- lib/default.nix
- lib/lists.nix
- lib/mkFlake/default.nix
- lib/mkFlake/evalArgs.nix
This is a simpler version of #218 that moves flake logic to lib and adds a module to evaluate devos. This DOES NOT support out of tree usage, so if you were following any of the previous PR's, the doc sections/examples to use devos as a library will not work. There is work to make a cleaner api and only then will out of tree support work. Until then, this is still useful to simplify devos and clean up a lot of the implementation logic.
> Move flake implementation logic to lib

- profiles/core/default.nix
Looks like core does not include `lsusb` by default, now it does.
> core: add usbutils

- lib/mkFlake/evalArgs.nix
Just tried to drop the line and I realized the type for the attribute was wrong.
> evalFlakeArgs: fix userSpecialArgs defaults

- cachix/README.md
After the project rename the cachix documentation in `cachix/README.md` contains instructions that do not work (`cachix use divnix`).
Tested that `cachix use nrdxp` works and should have the intended effect.
> Fix documentation mistake after project rename

- lib/mkFlake/evalArgs.nix
This simply encodes the public facing portion of the api #232. @blaggacao and I ended up changing the API after some discussion, so this is the most updated version of the planned API.
> Update evalArgs to match the new planned API

- lib/attrs.nix
- lib/devos/default.nix
- lib/devos/devosSystem.nix
- lib/devos/mkHomeConfigurations.nix
- lib/devos/mkHosts.nix
- lib/devos/mkNodes.nix
- lib/devos/mkPackages.nix
- lib/devos/mkPkgs.nix
- lib/devos/mkProfileAttrs.nix
- lib/devos/mkSuites.nix
- lib/devos/recImport.nix
- lib/flake.nix
- lib/lists.nix
- lib/mkFlake/default.nix
- lib/pkgs-lib/default.nix
- lib/strings.nix
for clarity's sake, expose which function uses final and prev, so that
people can have a clearer understanding how they relate to each other
in terms of dependencies.
also a simple `{ lib = final; }` probably does not warrant a complete
callLibs obscurization.
> ref: reduce exposure to callLibs

- lib/mkFlake/evalArgs.nix
allow lists, nested lists, and non-lists for list like options
drop config.<name>.externalModules
> used coercedTo for typing and improve options

- lib/mkFlake/evalArgs.nix
in devos, we differentiate clearly between home and os
configuration, reason for which we are more precise by not naming
after the (more generic) fup API.
> ref: config -> hosts | nixos -> os

- flake.lock
- lib/devos/default.nix
- lib/devos/devosSystem.nix
- lib/devos/mkHomeConfigurations.nix
- lib/devos/mkHosts.nix
- lib/devos/mkPackages.nix
- lib/devos/mkPkgs.nix
- lib/devos/mkProfileAttrs.nix
- lib/flake.lock
- lib/flake.nix
- lib/jobs/default.nix
- lib/jobs/mkFlakeDoc.nix
- lib/mkFlake/default.nix
- lib/mkFlake/evalArgs.nix
- lib/mkFlake/evalOldArgs.nix
- lib/pkgs-lib/default.nix
- lib/pkgs-lib/shell/default.nix
- lib/pkgs-lib/tests/default.nix
- lib/tests/default.nix
Also format all files and add a flake.lock for lib
for a folder thats meant to work on other flakes theres never a reason it should need to refer to itself, only other flakes. So "self" and "inputs" are better namings for these variables. The userFlake* is redundant and confusing, when trying to call the functions its hard to figure out how to use them when there are two lines of arguments to figure out. 
Many of the functions don't even need this much information(ie mkHomeConfigurations and mkPkgs).
lib needs a flake.lock, because it is a flake we want others to  use. Also having to regenerate it every time its used makes no sense.
This also gets develop to pass `flake check` which it didn't because of deploy having a `utils.follows = "utils"`.
> lib: one line for arguments, drop userFlake*

- flake.lock
- lib/devos/devosSystem.nix
- lib/devos/mkHosts.nix
- lib/flake.nix
- lib/modules.nix
Currently devosSystem and mkHosts a few modules in themselves. This ends up with them containing lots of code thats not directly related to its purpose. So I extracted those modules into their own file `lib/modules.nix` and namespace `lib.modules`. Each attribute is a module or a function to a module to describe what each module depends on. These are then used in devosSystem and mkHosts.
This should make rebase on fup easier, you can just drop lines in each module or remove unnecessary dependencies much easier if they have their own dedicated file.
> create lib.modules to store all devos modules

- lib/devos/mkHosts.nix
- lib/pkgs-lib/tests/default.nix
Now that profiles test is done dynamically - first available host - we likely need to include the host configuration itself. I have profiles that depend on the domain being set, which how I ran into this, and I think other problems might occur if we don't include the full host in the profiles test.
targeting core, since its a small bug fix and was planned to make into a release.
> profilesTest/mkHosts: include host's configuration

- flake.lock
- flake.nix
- lib/devos/mkHomeConfigurations.nix
- lib/mkFlake/default.nix
- lib/modules.nix
- lib/pkgs-lib/tests/default.nix
- modules/customBuilds.nix
have mkHomeConfiguration create its own custom build within the function
create a externalModule for customBuilds so its easy to add more
closes #170
> pass builderArgs to config and extract builds

- default.nix
Looks like it was just a path error.
fixes #285
> default.nix: fix path to compat

- doc/secrets.md
- flake.lock
- flake.nix
- overlays/overrides.nix
- profiles/core/default.nix
- secrets/.gitattributes
- secrets/secrets.nix
AFAICT This is mostly a documentation thing. But with divnix/devlib#2 we can now add agenix to the devshell.
> Agenix integration

- doc/start/index.md
This resolves #292.
One can use sudo if the user they are using is not trusted by their current system (either their custom NixOS or the NixOS live USB)
> Added note about cache in start/index.md docs

- doc/SUMMARY.md
- doc/flk/doi.md
- modules/customBuilds.nix
https://github.com/divnix/digga/pull/42
> customBuilds: add digitalOcean

- flake.nix
At least we don't find ourselves with strange module signatures
and use something that looks like a dedicated namespace within
he module system: `config.lib`
---
```shell
➜  devos git:(da/pass-lib-as-config-lib) rg ourLib
➜  devos git:(da/pass-lib-as-config-lib) # nothing found
```
> ref: pass our lib as lib.our to the module system

- flake.nix
- overlays/overrides.nix
using `lib.composeExtensions` for packageOverrides is more idiomatic.
Fixes: https://github.com/divnix/devos/pull/325#pullrequestreview-687772802
such as 
```
python3 = pkgs.python3.override (old: {
5 │ │ packageOverrides =
4 │ │ │ pkgs.lib.composeExtensions
3 │ │ │ │ (old.packageOverrides or (_: _: { }))
2 │ │ │ │ packageOverrides;
1 │ });
```
> Fix: Haskell overlay

- profiles/core/default.nix
gotop is unmaintained, unless someone has a better alternative, it looks like bottom is the new goto
> core: use bottom instead of gotop

- .gitignore
- flake.lock
- flake.nix
- pkgs/bud/default.nix
- pkgs/bud/get.bash
- shell/default.nix
- shell/hooks/default.nix
- shell/hooks/pre-commit.sh
This is tested via https://github.com/divnix/devos/pull/334
If that is green, we can merge there update the ref to `digga` here and run the CI here again.
> ref: move devshell module here to `devos` again

- flake.lock
- flake.nix
To update your `devos`, simply add the [anti-corruption layer lines](https://github.com/divnix/devos/pull/342/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R44-R51)
> imp: reduce flake inputs footprint and increase conciseness

- flake.lock
- flake.nix
- users/nixos/default.nix
According to https://github.com/nix-community/home-manager/issues/2161
there might be a better formal distinction between host-spaced and
portable arch-spaced hm users in the future.
> imp: add portable user definition

- flake.lock
- modules/customBuilds.nix
- modules/hm-system-defaults.nix
- ref: make hm common module explicit
- ref: cleanup hm build
> hm cleanup

- .github/workflows/check.yml
- .github/workflows/mdbook_docs.yml
- doc/CONTRIBUTING.md
Addresses the broken CI workflows mentioned in #369 by allowing workflow triggers on pushes to the `master` branch since `main` doesn't exist. This does not necessarily mean #369 can be closed since ideally `master` will be replaced with `main` entirely.
> Trigger CI workflows on pushes to both `main` and `master` + Update PR target branch guideline

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/release.yml
- .gitignore
- bud/get.bash
- doc/concepts/profiles.md
- doc/concepts/users.md
- doc/integrations/deploy.md
- doc/integrations/nvfetcher.md
- doc/start/from-nixos.md
- doc/start/index.md
- doc/tests.md
Fixes #366 
~Blocked by #369 — the docs cannot be updated until the docs workflow is running again. The site hasn't been built since last month despite other recent updates to docs on `master`.~ ✅
> Replace references to `flk` and `core` with `bud` and `master`

- .github/workflows/check.yml
- .github/workflows/mdbook_docs.yml
See #369
I should have removed these in #371
> Remove lingering references to `main` in workflow configs

- doc/secrets.md
- secrets/.gitattributes
- shell/devos.nix
`git crypt` is rather hard to use, and overlaps with `agenix` in a lot of circumstances. Using both of them at the same time can result in double-encrypted files, causing issues that are hard to debug. This PR removes git-crypt from the installation and documentation, favoring agenix instead.
> Remove git crypt, update docs

- users/nixos/default.nix
`uid = 1000` is an unreasonable default for an examplary user nixos, because someone trying DevOs on a working NixOS installation likely has their own user with uid = 1000 already. The code thus renders `/etc/passwd` invalid preventing user from logging in
> Do not hardcode UID for the exemplary user

- doc/secrets.md
The path for decrypted secrets has changed upstream.
> Update secrets path

- doc/concepts/users.md
While muddling through #381, I realized the docs had a reference to an option that had been renamed.
I'm not sure yet whether any changes should be made to the example in the previous section, as the default seems to be to pull stuff in from `hmUsers` rather than directly specifying options like the example does, but I'm not sure what we'd consider best practice there.
> Fix outdated option name

- flake.lock
- flake.nix
There is a bug in the input-output-hk fork
> flake: switch back to serokell deploy input

- deprecated.nix
- flake.nix
- src/mkFlake/options.nix
I'm keeping the deprecation code for `externalModules` still, since there hasn't been a proper release that included that code.
> Remove suites, profiles, and old importer code

- shell.nix
Darwin's use of BSD `sed` breaks here because BSD `sed` has a different
argument signature.
Spun off from #438 as suggested in https://github.com/divnix/digga/pull/438#discussion_r815551027
> fix: use gnu sed in shell tests for cross-platform compatibility

- .github/workflows/check.yml
- README.md
- bors.toml
- doc/CONTRIBUTING.md
- we've been having some problems with bors lately
- retrying a bors command notifies everyone watching the repo, which stinks when bors is behaving unexpectedly
- we really only make use of a very simple workflow which could be accomplished with GitHub Actions alone
> ci: remove bors integration + use native github actions for pull request checks

- examples/devos/flake.lock
- examples/devos/flake.nix
- examples/devos/shell/devos.nix
- flake.lock
- flake.nix
- src/mkFlake/fup-adapter.nix
- src/modules.nix
nixos-generators now has --flake support, so theres no reason for us to export all the builds here. Lets just offload this responsibility to nixos-generators.
Somewhat blocked by nix-community/nixos-generators#138, so that we don't need to make our hosts overridable.
> Remove customBuilds, nixos-generate has --flake

- .github/workflows/check.yml
I've been noticing some workflow runs are failing due to rate limiting. This should hopefully resolve those issues by following the example in https://github.com/cachix/install-nix-action#usage-with-flakes
> ci updates + authenticated requests

- doc/start/index.md
Fixes #458
The command for users without flakes support is untested, I just modified the earlier `flake init` command using the digga shell
> 458 Onboarding docs get you to a nix-shell

- README.md
https://github.com/divnix/digga/pull/435 migrated the README to a new location, but didn't migrate this link.
> Fix shoulders of giants link in README

- README.md
Hello!
I propose adding my repo as another example repo in the README.
The interesting stuff would be the fact that I mix my home-manager configs with my system configs and maybe the RaspberryPi deployment.
I won't feel bad if you reject the PR ;)
> Add another example repo to README

- .gitignore
- examples/devos/flake.nix
- examples/devos/lib/compat/default.nix
- examples/devos/shell/devos.nix
- examples/devos/shell/hooks/pre-commit.sh
I unpinned flake-compat, favouring whatever rev is put in the lock file instead and checked the `editorconfig-checker` exit code directly, [avoiding potential issues](https://github.com/koalaman/shellcheck/wiki/SC2181). The issue causing the tempfix [has been resolved](https://github.com/numtide/devshell/issues/26).
> Devos Refactor

- doc/start/index.md
- examples/devos/flake.lock
- examples/groupByConfig/flake.lock
- examples/hmOnly/flake.lock
- shell/default.nix
- shell/pre-commit.sh
Follow up to #495. There was an issue where upstream breaking changes bypassed CI checks as CI was checking against the latest upstream only once. Keeping the examples lock files ensures reproducibility, ensures CI checks are reliable, and prevents unexpected check failures. Manually updating lock files is annoying so I added commands to the devshell.
> Persist examples lock files

- examples/devos/flake.lock
- examples/devos/flake.nix
- examples/groupByConfig/flake.lock
- examples/groupByConfig/flake.nix
- examples/hmOnly/flake.lock
- examples/hmOnly/flake.nix
- examples/hmOnly/home/users/testuser.nix
- flake.lock
- flake.nix
- src/mkFlake/outputs-builder.nix
This commit updates the home-manager flake input to the 22.11 release and creates additional support for the new homeManagerConfiguration setup that is introduced there.
~The new release of home-manager introduces a dependency to numtide/flake-utils, which already exists in deploy-rs. To reduce the amount of different versions, this commit makes the input of deploy-rs follow the respective one of home-manager.~ (see my comment below on why I dropped this)
Regarding homeManagerConfiguration, some arguments that were previously in use, now need to be used inside the new modules argument (check [here][hm-22.11-highlights] for more details).
The stateVersion is additionally explicitly defined to be the same as the home-manager's release version, so that existing configurations do not break …
> Update home-manager to 22.11

- examples/devos/lib/default.nix
Hi all. I wanted to put custom functions in the /lib/ directory, but lib/default.nix was basically empty and I couldn't find anything in the docs about it. After a while I figured it out, and I thought it would help future noobs if there was a note in the file explaining itself.
Thanks for the great template!
> :pencil: devos: clarify how to use /lib/
